# The version of the docker-compose.
version: "3.8"
# Telling docker-compose to build the client and server images and run them in containers.
services:
  database:
    image: mongo
    container_name: mongo-db
    volumes:
      - /Users/anna/Sites/mern/mongo-db-backup:/data/db
    networks:
      - mern-network
  server:
    # Telling docker-compose to build the client image using the Dockerfile in the server directory.
    build: ./back
    container_name: node-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - mern-network
  client:
    # Telling docker-compose to build the client image using the Dockerfile in the client directory.
    build: ./mern-blog-frontend
    # Giving the container a name.
    container_name: react-ui
    # Mapping the port 3000 on the host machine to the port 3000 on the container.
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - server
    networks:
      - mern-network
networks:
  mern-network:
    driver: bridge
